In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('weather.csv', encoding='latin1')
data

,Sr. No.,Date2,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,...,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure,Year,Day,Date
0,1,01-01-2022,37.8,35,12.7,29.7,26.4,36.8,274,0.00,...,29.596,41.4,59.0,40.0,01-01-2022,1,0.166,2022,1,01-01-2022
1,2,02-01-2022,43.2,32,14.7,29.5,12.8,18.0,240,0.00,...,29.268,35.7,51.0,52.0,02-01-2022,1,0.401,2022,2,02-01-2022
2,3,03-01-2022,25.7,60,12.7,29.7,8.3,12.2,290,0.00,...,29.260,25.3,38.0,41.0,03-01-2022,1,0.972,2022,3,03-01-2022
3,4,04-01-2022,9.3,67,0.1,30.4,2.9,4.5,47,0.00,...,30.227,12.7,20.0,32.0,04-01-2022,1,0.339,2022,4,04-01-2022
4,5,05-01-2022,23.5,30,-5.3,29.9,16.7,23.1,265,0.00,...,29.568,38.0,53.0,32.0,05-01-2022,1,0.665,2022,5,05-01-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3896,3899,25-07-2022,62.8,60,48.1,29.7,2.5,4.0,242,0.33,...,29.645,8.1,17.3,77.5,25-07-2022,7,0.136,2033,25,25-07-2033
3897,3900,26-07-2022,60.6,68,48.9,29.8,1.7,2.9,357,0.33,...,29.745,11.5,15.0,77.5,26-07-2022,7,0.185,2033,26,26-07-2033
3898,3901,27-07-2022,61.7,64,47.4,29.9,2.2,4.0,66,0.33,...,29.781,13.8,18.4,78.2,27-07-2022,7,0.16,2033,27,27-07-2033
3899,3902,28-07-2022,60.5,61,45.3,29.7,4.0,6.2,248,0.35,...,29.675,17.3,26.5,77.6,28-07-2022,7,0.11700000000000088;,2033,28,28-07-2033
3900,3903,28-07-2022,60.5,61,45.3,29.7,4.0,6.2,248,0.35,...,29.675,17.3,26.5,77.6,28-07-2022,7,0.11700000000000088;,2033,28,28-07-2033

In [3]:
data.head()

,Sr. No.,Date2,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,...,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure,Year,Day,Date
0,1,01-01-2022,37.8,35,12.7,29.7,26.4,36.8,274,0.0,...,29.596,41.4,59.0,40.0,01-01-2022,1,0.166,2022,1,01-01-2022
1,2,02-01-2022,43.2,32,14.7,29.5,12.8,18.0,240,0.0,...,29.268,35.7,51.0,52.0,02-01-2022,1,0.401,2022,2,02-01-2022
2,3,03-01-2022,25.7,60,12.7,29.7,8.3,12.2,290,0.0,...,29.260,25.3,38.0,41.0,03-01-2022,1,0.972,2022,3,03-01-2022
3,4,04-01-2022,9.3,67,0.1,30.4,2.9,4.5,47,0.0,...,30.227,12.7,20.0,32.0,04-01-2022,1,0.339,2022,4,04-01-2022
4,5,05-01-2022,23.5,30,-5.3,29.9,16.7,23.1,265,0.0,...,29.568,38.0,53.0,32.0,05-01-2022,1,0.665,2022,5,05-01-2022

# drop columns

In [4]:
data=data.drop('Sr. No.', axis=1)
data=data.drop('Date2',axis=1)
data=data.drop('Date1',axis=1)

In [5]:
data

,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,...,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Month,diff_pressure,Year,Day,Date
0,37.8,35,12.7,29.7,26.4,36.8,274,0.00,0.00,0,...,29.762,29.596,41.4,59.0,40.0,1,0.166,2022,1,01-01-2022
1,43.2,32,14.7,29.5,12.8,18.0,240,0.00,0.00,0,...,29.669,29.268,35.7,51.0,52.0,1,0.401,2022,2,02-01-2022
2,25.7,60,12.7,29.7,8.3,12.2,290,0.00,0.00,0,...,30.232,29.260,25.3,38.0,41.0,1,0.972,2022,3,03-01-2022
3,9.3,67,0.1,30.4,2.9,4.5,47,0.00,0.00,0,...,30.566,30.227,12.7,20.0,32.0,1,0.339,2022,4,04-01-2022
4,23.5,30,-5.3,29.9,16.7,23.1,265,0.00,0.00,0,...,30.233,29.568,38.0,53.0,32.0,1,0.665,2022,5,05-01-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3896,62.8,60,48.1,29.7,2.5,4.0,242,0.33,4.47,0,...,29.781,29.645,8.1,17.3,77.5,7,0.136,2033,25,25-07-2033
3897,60.6,68,48.9,29.8,1.7,2.9,357,0.33,4.47,0,...,29.930,29.745,11.5,15.0,77.5,7,0.185,2033,26,26-07-2033
3898,61.7,64,47.4,29.9,2.2,4.0,66,0.33,4.47,0,...,29.941,29.781,13.8,18.4,78.2,7,0.16,2033,27,27-07-2033
3899,60.5,61,45.3,29.7,4.0,6.2,248,0.35,4.49,0,...,29.792,29.675,17.3,26.5,77.6,7,0.11700000000000088;,2033,28,28-07-2033
3900,60.5,61,45.3,29.7,4.0,6.2,248,0.35,4.49,0,...,29.792,29.675,17.3,26.5,77.6,7,0.11700000000000088;,2033,28,28-07-2033

# Duplicated rows

In [6]:
# print the duplicated rows
data[data.duplicated()]

,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,...,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Month,diff_pressure,Year,Day,Date
3900,60.5,61,45.3,29.7,4.0,6.2,248,0.35,4.49,0,...,29.792,29.675,17.3,26.5,77.6,7,0.11700000000000088;,2033,28,28-07-2033

In [7]:
# drop duplicates
data=data.drop_duplicates()

In [8]:
data

,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,...,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Month,diff_pressure,Year,Day,Date
0,37.8,35,12.7,29.7,26.4,36.8,274,0.00,0.00,0,...,29.762,29.596,41.4,59.0,40.0,1,0.166,2022,1,01-01-2022
1,43.2,32,14.7,29.5,12.8,18.0,240,0.00,0.00,0,...,29.669,29.268,35.7,51.0,52.0,1,0.401,2022,2,02-01-2022
2,25.7,60,12.7,29.7,8.3,12.2,290,0.00,0.00,0,...,30.232,29.260,25.3,38.0,41.0,1,0.972,2022,3,03-01-2022
3,9.3,67,0.1,30.4,2.9,4.5,47,0.00,0.00,0,...,30.566,30.227,12.7,20.0,32.0,1,0.339,2022,4,04-01-2022
4,23.5,30,-5.3,29.9,16.7,23.1,265,0.00,0.00,0,...,30.233,29.568,38.0,53.0,32.0,1,0.665,2022,5,05-01-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,64.1,62,49.8,29.6,3.6,5.8,240,0.24,4.38,0,...,29.686,29.577,15.0,25.3,77.4,7,0.109,2033,24,24-07-2033
3896,62.8,60,48.1,29.7,2.5,4.0,242,0.33,4.47,0,...,29.781,29.645,8.1,17.3,77.5,7,0.136,2033,25,25-07-2033
3897,60.6,68,48.9,29.8,1.7,2.9,357,0.33,4.47,0,...,29.930,29.745,11.5,15.0,77.5,7,0.185,2033,26,26-07-2033
3898,61.7,64,47.4,29.9,2.2,4.0,66,0.33,4.47,0,...,29.941,29.781,13.8,18.4,78.2,7,0.16,2033,27,27-07-2033
3899,60.5,61,45.3,29.7,4.0,6.2,248,0.35,4.49,0,...,29.792,29.675,17.3,26.5,77.6,7,0.11700000000000088;,2033,28,28-07-2033

# Renaming the columns

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3900 entries, 0 to 3899
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0    Temperature              3900 non-null   float64
 1    Average humidity (%      3900 non-null   int64
 2    Average dewpoint (°F     3900 non-null   float64
 3    Average barometer (in    3900 non-null   float64
 4    Average windspeed (mph   3900 non-null   float64
 5    Average gustspeed (mph   3900 non-null   float64
 6    Average direction (°deg  3900 non-null   int64
 7    Rainfall for month (in   3900 non-null   float64
 8   Rainfall for year (in     3900 non-null   float64
 9    Maximum rain per minute  3900 non-null   int64
 10   Maximum temperature (°F  3900 non-null   float64
 11   Minimum temperature (°F  3900 non-null   float64
 12   Maximum humidity (%      3900 non-null   int64
 13   Minimum humidity (%      3900 non-null   int64
 14   Maximum pressure         3900 non-null   float64
 15   Minimum pressure         3900 non-null   float64
 16   Maximum windspeed (mph   3900 non-null   float64
 17   Maximum gust speed (mph  3900 non-null   float64
 18   Maximum heat index (°F   3900 non-null   float64
 19   Month                    3900 non-null   int64
 20   diff_pressure            3900 non-null   object
 21  Year                      3900 non-null   int64
 22  Day                       3900 non-null   int64
 23  Date                      3900 non-null   object
dtypes: float64(14), int64(8), object(2)
memory usage: 761.7+ KB

In [10]:
data = data.rename(columns={' Average humidity (%': 'Average_humidity_%',
                            ' Average dewpoint (°F': 'Average_dewpoint_°F',
                            ' Average barometer (in': 'Average_barometer_in',
                            ' Average windspeed (mph': 'Average_windspeed_mph',
                            ' Average gustspeed (mph': 'Average_gustspeed_mph',
                            ' Average direction (°deg': 'Average_direction_°deg',
                            ' Rainfall for month (in': 'Rainfall_for_month_in',
                            'Rainfall for year (in': 'Rainfall_for_year_in',
                            ' Maximum rain per minute': 'Maximum_rain_per_minute',
                            ' Maximum temperature (°F': 'Maximum_temperature_°F',
                            ' Minimum temperature (°F': 'Minimum_temperature_°F',
                            ' Maximum humidity (%': 'Maximum_humidity_%',
                            ' Minimum humidity (%': 'Minimum_humidity_%',
                            ' Maximum pressure': 'Maximum_pressure',
                            ' Minimum pressure': 'Minimum_pressure',
                            ' Maximum windspeed (mph': 'Maximum_windspeed_mph',
                            ' Maximum gust speed (mph': 'Maximum_gust_speed_mph',
                            ' Maximum heat index (°F': 'Maximum_heat_index_°F',
                            ' Temperature': 'Temperature',
                            ' Month': 'Month',
                            ' diff_pressure': 'diff_pressure'
                           })

In [11]:
data.columns

Index(['Temperature', 'Average_humidity_%', 'Average_dewpoint_°F',
       'Average_barometer_in', 'Average_windspeed_mph',
       'Average_gustspeed_mph', 'Average_direction_°deg',
       'Rainfall_for_month_in', 'Rainfall_for_year_in',
       'Maximum_rain_per_minute', 'Maximum_temperature_°F',
       'Minimum_temperature_°F', 'Maximum_humidity_%', 'Minimum_humidity_%',
       'Maximum_pressure', 'Minimum_pressure', 'Maximum_windspeed_mph',
       'Maximum_gust_speed_mph', 'Maximum_heat_index_°F', 'Month',
       'diff_pressure', 'Year', 'Day', 'Date'],
      dtype='object')

# Handling null values

In [12]:
# Checking null values
data.isnull().sum()

Temperature                0
Average_humidity_%         0
Average_dewpoint_°F        0
Average_barometer_in       0
Average_windspeed_mph      0
Average_gustspeed_mph      0
Average_direction_°deg     0
Rainfall_for_month_in      0
Rainfall_for_year_in       0
Maximum_rain_per_minute    0
Maximum_temperature_°F     0
Minimum_temperature_°F     0
Maximum_humidity_%         0
Minimum_humidity_%         0
Maximum_pressure           0
Minimum_pressure           0
Maximum_windspeed_mph      0
Maximum_gust_speed_mph     0
Maximum_heat_index_°F      0
Month                      0
diff_pressure              0
Year                       0
Day                        0
Date                       0
dtype: int64

# Replacing values

In [13]:
# Replace
data=data.replace('0.11700000000000088;','0.11700000000000088')
data

,Temperature,Average_humidity_%,Average_dewpoint_°F,Average_barometer_in,Average_windspeed_mph,Average_gustspeed_mph,Average_direction_°deg,Rainfall_for_month_in,Rainfall_for_year_in,Maximum_rain_per_minute,...,Maximum_pressure,Minimum_pressure,Maximum_windspeed_mph,Maximum_gust_speed_mph,Maximum_heat_index_°F,Month,diff_pressure,Year,Day,Date
0,37.8,35,12.7,29.7,26.4,36.8,274,0.00,0.00,0,...,29.762,29.596,41.4,59.0,40.0,1,0.166,2022,1,01-01-2022
1,43.2,32,14.7,29.5,12.8,18.0,240,0.00,0.00,0,...,29.669,29.268,35.7,51.0,52.0,1,0.401,2022,2,02-01-2022
2,25.7,60,12.7,29.7,8.3,12.2,290,0.00,0.00,0,...,30.232,29.260,25.3,38.0,41.0,1,0.972,2022,3,03-01-2022
3,9.3,67,0.1,30.4,2.9,4.5,47,0.00,0.00,0,...,30.566,30.227,12.7,20.0,32.0,1,0.339,2022,4,04-01-2022
4,23.5,30,-5.3,29.9,16.7,23.1,265,0.00,0.00,0,...,30.233,29.568,38.0,53.0,32.0,1,0.665,2022,5,05-01-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,64.1,62,49.8,29.6,3.6,5.8,240,0.24,4.38,0,...,29.686,29.577,15.0,25.3,77.4,7,0.109,2033,24,24-07-2033
3896,62.8,60,48.1,29.7,2.5,4.0,242,0.33,4.47,0,...,29.781,29.645,8.1,17.3,77.5,7,0.136,2033,25,25-07-2033
3897,60.6,68,48.9,29.8,1.7,2.9,357,0.33,4.47,0,...,29.930,29.745,11.5,15.0,77.5,7,0.185,2033,26,26-07-2033
3898,61.7,64,47.4,29.9,2.2,4.0,66,0.33,4.47,0,...,29.941,29.781,13.8,18.4,78.2,7,0.16,2033,27,27-07-2033
3899,60.5,61,45.3,29.7,4.0,6.2,248,0.35,4.49,0,...,29.792,29.675,17.3,26.5,77.6,7,0.11700000000000088,2033,28,28-07-2033

In [14]:
# Data types
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3900 entries, 0 to 3899
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Temperature              3900 non-null   float64
 1   Average_humidity_%       3900 non-null   int64
 2   Average_dewpoint_°F      3900 non-null   float64
 3   Average_barometer_in     3900 non-null   float64
 4   Average_windspeed_mph    3900 non-null   float64
 5   Average_gustspeed_mph    3900 non-null   float64
 6   Average_direction_°deg   3900 non-null   int64
 7   Rainfall_for_month_in    3900 non-null   float64
 8   Rainfall_for_year_in     3900 non-null   float64
 9   Maximum_rain_per_minute  3900 non-null   int64
 10  Maximum_temperature_°F   3900 non-null   float64
 11  Minimum_temperature_°F   3900 non-null   float64
 12  Maximum_humidity_%       3900 non-null   int64
 13  Minimum_humidity_%       3900 non-null   int64
 14  Maximum_pressure         3900 non-null   float64
 15  Minimum_pressure         3900 non-null   float64
 16  Maximum_windspeed_mph    3900 non-null   float64
 17  Maximum_gust_speed_mph   3900 non-null   float64
 18  Maximum_heat_index_°F    3900 non-null   float64
 19  Month                    3900 non-null   int64
 20  diff_pressure            3900 non-null   object
 21  Year                     3900 non-null   int64
 22  Day                      3900 non-null   int64
 23  Date                     3900 non-null   object
dtypes: float64(14), int64(8), object(2)
memory usage: 761.7+ KB

In [15]:
# change data types
data['diff_pressure'] = data['diff_pressure'].astype('float64')

In [16]:
data

,Temperature,Average_humidity_%,Average_dewpoint_°F,Average_barometer_in,Average_windspeed_mph,Average_gustspeed_mph,Average_direction_°deg,Rainfall_for_month_in,Rainfall_for_year_in,Maximum_rain_per_minute,...,Maximum_pressure,Minimum_pressure,Maximum_windspeed_mph,Maximum_gust_speed_mph,Maximum_heat_index_°F,Month,diff_pressure,Year,Day,Date
0,37.8,35,12.7,29.7,26.4,36.8,274,0.00,0.00,0,...,29.762,29.596,41.4,59.0,40.0,1,0.166,2022,1,01-01-2022
1,43.2,32,14.7,29.5,12.8,18.0,240,0.00,0.00,0,...,29.669,29.268,35.7,51.0,52.0,1,0.401,2022,2,02-01-2022
2,25.7,60,12.7,29.7,8.3,12.2,290,0.00,0.00,0,...,30.232,29.260,25.3,38.0,41.0,1,0.972,2022,3,03-01-2022
3,9.3,67,0.1,30.4,2.9,4.5,47,0.00,0.00,0,...,30.566,30.227,12.7,20.0,32.0,1,0.339,2022,4,04-01-2022
4,23.5,30,-5.3,29.9,16.7,23.1,265,0.00,0.00,0,...,30.233,29.568,38.0,53.0,32.0,1,0.665,2022,5,05-01-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,64.1,62,49.8,29.6,3.6,5.8,240,0.24,4.38,0,...,29.686,29.577,15.0,25.3,77.4,7,0.109,2033,24,24-07-2033
3896,62.8,60,48.1,29.7,2.5,4.0,242,0.33,4.47,0,...,29.781,29.645,8.1,17.3,77.5,7,0.136,2033,25,25-07-2033
3897,60.6,68,48.9,29.8,1.7,2.9,357,0.33,4.47,0,...,29.930,29.745,11.5,15.0,77.5,7,0.185,2033,26,26-07-2033
3898,61.7,64,47.4,29.9,2.2,4.0,66,0.33,4.47,0,...,29.941,29.781,13.8,18.4,78.2,7,0.160,2033,27,27-07-2033
3899,60.5,61,45.3,29.7,4.0,6.2,248,0.35,4.49,0,...,29.792,29.675,17.3,26.5,77.6,7,0.117,2033,28,28-07-2033

# converting to csv

In [17]:
data.to_csv('weather_cleaned1.csv')